# Generated by Django 4.0.4 on 2022-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_left_hand_compatible',
            field=models.BooleanField(default=False),
        ),
    ]
