# Generated by Django 4.0.4 on 2022-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_product_is_left_hand_compatible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='review',
        ),
        migrations.AddField(
            model_name='purchase',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
